ALTER TABLE churches ADD COLUMN IF NOT EXISTS tagline VARCHAR(255);
ALTER TABLE churches ADD COLUMN IF NOT EXISTS mission TEXT;
ALTER TABLE churches ADD COLUMN IF NOT EXISTS service_times TEXT;
ALTER TABLE churches ADD COLUMN IF NOT EXISTS website TEXT;
ALTER TABLE churches ADD COLUMN IF NOT EXISTS facebook_url TEXT;
ALTER TABLE churches ADD COLUMN IF NOT EXISTS instagram_url TEXT;
ALTER TABLE churches ADD COLUMN IF NOT EXISTS youtube_url TEXT;
ALTER TABLE churches ADD COLUMN IF NOT EXISTS theme_color VARCHAR(20) DEFAULT '#4f46e5';
